function AnalysisGUI()
    % Create the figure
    fig = figure('Name', 'Data Plotter and Interpolator', ...
                 'NumberTitle', 'off', ...
                 'Position', [100, 100, 700, 500]);

    % Add a button for selecting files
    selectFileBtn = uicontrol('Style', 'pushbutton', ...
                              'Position', [20, 440, 120, 25], ...
                              'String', 'Select File', ...
                              'Callback', @selectFileCallback);

    % Add an axes for plotting
    ax = axes('Units', 'pixels', ...
              'Position', [180, 50, 490, 420]);

    % Add a field for y value input
    yValueLabel = uicontrol('Style', 'text', ...
                            'Position', [20, 400, 120, 25], ...
                            'String', 'Enter Signal Value:');
    yValueEdit = uicontrol('Style', 'edit', ...
                           'Position', [20, 370, 120, 25], ...
                           'String', '');

    % Add a button for interpolation
    interpolateBtn = uicontrol('Style', 'pushbutton', ...
                               'Position', [20, 340, 120, 25], ...
                               'String', 'Interpolate', ...
                               'Callback', @interpolateCallback);

    % Add a label for displaying the interpolated X value or range info
    interpolatedXLabel = uicontrol('Style', 'text', ...
                                   'Position', [0, 310, 160, 25], ...
                                   'String', 'Current(uA):');

    % Store components in the figure's UserData for easy access
    fig.UserData.ax = ax;
    fig.UserData.yValueEdit = yValueEdit;
    fig.UserData.interpolatedXLabel = interpolatedXLabel;
    fig.UserData.data = [];
end
